name: simple_auth_flutter_login_fix
description: (Fork of) Simple Auth is the simplest way to authenticate your users/apis. This plugin will securely store tokens/credentials as well as automatically present login UI when needed. This version fixes ios done button issue on login page.
version: 1.0.2
homepage: https://github.com/mohammad-aqib/simple_auth

environment:
    sdk: '>=2.12.0 <3.0.0'
    flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter
  simple_auth: ^2.0.10
flutter:
  plugin:
    platforms:
      android:
        package: clancey.simpleauth.simpleauthflutter
        pluginClass: SimpleAuthFlutterPlugin
      ios:
        pluginClass: SimpleAuthFlutterPlugin
      macos:
        pluginClass: SimpleAuthFlutterPlugin

false_secrets:
 - /example/lib/main.dart